pipeline{
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url : 'https://github.com/hy-git-111/Jenkins-FreestyleJob.git', branch: 'main'
                echo '소스코드를 git 저장소에서 성공적으로 가져왔습니다.'
            }
        }
        stage('setup') {
            steps {
                dir('250502_jenkins-pipelinejob_2') {
                sh './build.sh'
                echo "Python 환경을 설정합니다."
                echo "pytest 설치 완료"
                }
            }
        }
        stage('Test') {
            steps {
                echo "pytest를 사용해서 테스트를 실행합니다."
                sh 'pytest ./pytest.py'
                echo "테스트 완료."
            }
        }
    }
}