pipeline{
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: '빌드할 git branch')
    }
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
            }
        }
        stage('Build') {
            steps {
                dir('250502_jenkins-pipelinejob') {
                    sh './build.sh'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Simulating test command"'
            }
        }
    }
}